### ISSUE TITLE
Lose current window focus when toggling airpod

### ISSUE THREAD

**Issue by Raphus-cucullatus** [jasonshanks/alfred-workflow-toggle-airpods#5]
This workflow is really handy to toggle AirPod connection, thanks!

However, after this workflow is run, my current window focus is lost: the application name in the top-left corner of the menu bar remains the same but the window frame is gray and keyboard input is not sent to the application anymore.  I have to click the window manually to regain the focus and continue my work.

After I removed this line, this issue disappeared:
https://github.com/jasonshanks/alfred-workflow-toggle-airpods/blob/5838759f8d15c0dbdcb457c87da4e760e5e57458/source/set_device.py#L18

May I ask what's the use of this line, and is it ok to remove it?

**Comment by jasonshanks** [comment]
Hey there :) Thanks for the shout out and for also piquing my interest in it again! I'm glad it's still useful to you.

I also verified that behaviour and seems to function fine without it. I've seen many other scripts beginning with this but nothing concrete about not having to specifically activate the System UI server anymore. You can see 2 lines down it's successfully talking to it so I've removed from the script as well and made it a permanent change.

How is the localisation for you? Feel free to contribute actual replacement terms in Mandarin i you want.

**Comment by Raphus-cucullatus** [comment]
Hi, thanks for your reply~

However, this issue still exists when I try the latest commit (0286b75291e79693de1735e48bc7e325dc2dc0d2).  What I did:
1. Pulled the latest commit.
2. Double clicked the `toggle-airpods.alfredworkflow` file to import.
3. Found the `set_device.py` file of this workflow (`~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.0F35FBCA-58C9-4A83-BF4F-2AF765D94B91/set_device.py` in my case), inserted the following code for localization:
```diff
@@ -11,11 +11,15 @@ if userLocale is "en_US" then
 else if userLocale is "ko-Kore_KR" then
     set user_connection to "연결"
     set user_disconnection to "연결 해제"
+
+else if userLocale is "zh_CN" then
+    set user_connection to "连接"
+    set user_disconnection to "断开连接"
 end if
 
 set device_name to "your_device_name"
```
3. Brought up Alfred input box and type "setairpods", and select my AirPods.
4. Typed "airpods" to connect to my AirPods.
5. Then my previous focus lost.

Instead, if I directly remove the line
```
activate application "SystemUIServer" 
```
in the `set_device.py` file (`~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.0F35FBCA-58C9-4A83-BF4F-2AF765D94B91/set_device.py` in my case), it works.

Do you know why this commit (0286b75291e79693de1735e48bc7e325dc2dc0d2) not work?  I will provide more info about my environment if needed.

**Comment by jasonshanks** [comment]
Hi Fan – good spot! I have:
- amended the setairpod script with the removal of this line (was only the connection script before)
- amended the setairpod script with the Chinese(mandarin) localisation I saw you had as well.
- re-exported the workflow again (calling it v1.3)
- updated the /source folder with a fresh copy of the workflow code folder
- updated the Readme file release notes with new version number and things improved.

You seem to know enough about what you are doing so I've added yourself and @novelview9 as contributors since I feel this is equally yours now as well. Might as well keep it alive together! Just follow same procedures as I outlined above if you're making a new commit/change. If you're new to git versioning development there's plenty of guides on here and beyond. For me I use a GUI app like the free [SourceTree app](https://www.sourcetreeapp.com), clone the repo directly in the app from the GitHub clone link. Edit the files in your code editor of choice. When it's fully tested on your computer, committing will publish it directly to GitHub for all.

**Comment by Raphus-cucullatus** [comment]
Hi, I'm glad to become a contributor!  

This commit (3fe10e5c5a081a4ada2464362c2b62c5bea44717) basically works but has a minor typo in `source/set_device.py`:

```applescript
end if
else if userLocale is "zh_CN" then
    set user_connection to "连接"
    set user_disconnection to "断开连接"
 end if
```

After the new code, there is a duplicated "end if" clause which can cause execution error.  I added a commit (20334c951ecbc1b5805167af342d0e401f71cfdf) to fix this.  (I didn't advance the version number since it is too small).  And this issue can be closed now, thanks again~
